config/routes.rb
Rails.application.routes.draw do
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by name: params[:session][:name].downcase
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to user
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new user_params
      if @user.save
        flash[:success] = "Register success"
        redirect_to users_path
      else
        flash[:success] = "Register failed"
        render :new
      end
    end
    
    def show
      @user = User.find_by id: params[:id]
    end

    private
    def user_params
      params.require(:user).permit :name, :password, :password_confirmation
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
        session[:user_id] = user.id
      end
    def log_out
        session.delete :user_id
      end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<label>Index Page</label>

app/views/users/new.html.erb
<div class="row">
  <div class="col-lg-offset-2">
    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-4">
          <%= f.submit "Register", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <label><%= @user.name %></label>
      </div>
      <%= link_to "Logout", logout_path, method: :delete %> 
    </div>
  </div>
</div>